"""qtd_questoes

Revision ID: 4c30d4026088
Revises: 
Create Date: 2023-07-06 21:45:04.934832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c30d4026088'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exame', sa.Column('qtd_questoes', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exame', 'qtd_questoes')
    # ### end Alembic commands ###
