"""init

Revision ID: 636cb17152b4
Revises: 8f01c8ce0733
Create Date: 2023-07-04 23:29:13.846218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636cb17152b4'
down_revision = '8f01c8ce0733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enunciado', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questao_ca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('resposta_correta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questao_ce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('resposta_correta', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alternativa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=255), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questao_id'], ['questao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alternativa')
    op.drop_table('questao_ce')
    op.drop_table('questao_ca')
    op.drop_table('questao')
    # ### end Alembic commands ###
