"""init

Revision ID: bb8761a71fca
Revises: 
Create Date: 2023-07-07 15:38:54.370305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8761a71fca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('qtd_questoes', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('horario_inicio', sa.DateTime(), nullable=False),
    sa.Column('horario_fim', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enunciado', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questao_ca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('resposta_correta', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questao_ce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('resposta_correta', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=9), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alternativa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=255), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questao_id'], ['questao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questao_exame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exame', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['exame'], ['exame.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questao_exame')
    op.drop_table('alternativa')
    op.drop_table('user')
    op.drop_table('questao_ce')
    op.drop_table('questao_ca')
    op.drop_table('questao')
    op.drop_table('exame')
    # ### end Alembic commands ###
