"""init

Revision ID: d53748c8d08b
Revises: 
Create Date: 2023-07-09 14:23:34.501565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53748c8d08b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('qtd_questoes', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('horario_inicio', sa.DateTime(), nullable=False),
    sa.Column('horario_fim', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ME', 'CE', 'CA'), nullable=False),
    sa.Column('enunciado', sa.String(length=255), nullable=False),
    sa.Column('correta', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=9), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('professor', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alternativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=255), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questao_exames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exame_id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exame_id'], ['exames.id'], ),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respostas_exame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exame_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exame_id'], ['exames.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respostas_questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('reposta_exame_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.ForeignKeyConstraint(['reposta_exame_id'], ['respostas_exame.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respostas_questoes')
    op.drop_table('respostas_exame')
    op.drop_table('questao_exames')
    op.drop_table('alternativas')
    op.drop_table('user')
    op.drop_table('questoes')
    op.drop_table('exames')
    # ### end Alembic commands ###
