"""responde_exame

Revision ID: f0de11814275
Revises: b3a323c900b6
Create Date: 2023-07-09 13:05:38.031731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0de11814275'
down_revision = 'b3a323c900b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('respostas_questoes', 'resposta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('respostas_questoes', sa.Column('resposta', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
