"""add valor exame

Revision ID: f17b079f13ab
Revises: 4c30d4026088
Create Date: 2023-07-06 21:53:59.960789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17b079f13ab'
down_revision = '4c30d4026088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exame', sa.Column('valor', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exame', 'valor')
    # ### end Alembic commands ###
