"""init

Revision ID: f2812ee7b745
Revises: 
Create Date: 2023-07-06 18:07:03.324864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2812ee7b745'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('horario_inicio', sa.DateTime(), nullable=False),
    sa.Column('horario_fim', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enunciado', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questao_ca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('resposta_correta', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questao_ce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('resposta_correta', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=9), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alternativa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=255), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questao_id'], ['questao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questoes',
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('exame_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exame_id'], ['exame.id'], ),
    sa.ForeignKeyConstraint(['questao_id'], ['questao.id'], ),
    sa.PrimaryKeyConstraint('questao_id', 'exame_id')
    )
    op.create_table('questoesCA',
    sa.Column('questaoCA_id', sa.Integer(), nullable=False),
    sa.Column('exame_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exame_id'], ['exame.id'], ),
    sa.ForeignKeyConstraint(['questaoCA_id'], ['questao_ca.id'], ),
    sa.PrimaryKeyConstraint('questaoCA_id', 'exame_id')
    )
    op.create_table('questoesCE',
    sa.Column('questaoCE_id', sa.Integer(), nullable=False),
    sa.Column('exame_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exame_id'], ['exame.id'], ),
    sa.ForeignKeyConstraint(['questaoCE_id'], ['questao_ce.id'], ),
    sa.PrimaryKeyConstraint('questaoCE_id', 'exame_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questoesCE')
    op.drop_table('questoesCA')
    op.drop_table('questoes')
    op.drop_table('alternativa')
    op.drop_table('user')
    op.drop_table('questao_ce')
    op.drop_table('questao_ca')
    op.drop_table('questao')
    op.drop_table('exame')
    # ### end Alembic commands ###
